# Generated by Django 5.1.15 on 2026-04-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile_tagline_alter_profile_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_zh_hans',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='description_ja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='description_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='description_zh_hans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study_ja',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study_pt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study_zh_hans',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='role_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='role_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='role_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='role_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='role_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='role_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='role_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='role_zh_hans',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='headline_ar',
            field=models.CharField(help_text='Pipe-separated roles for the typewriter animation, e.g. Software Engineer | System Architect', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='headline_de',
            field=models.CharField(help_text='Pipe-separated roles for the typewriter animation, e.g. Software Engineer | System Architect', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='headline_en',
            field=models.CharField(help_text='Pipe-separated roles for the typewriter animation, e.g. Software Engineer | System Architect', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='headline_es',
            field=models.CharField(help_text='Pipe-separated roles for the typewriter animation, e.g. Software Engineer | System Architect', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='headline_fr',
            field=models.CharField(help_text='Pipe-separated roles for the typewriter animation, e.g. Software Engineer | System Architect', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='headline_ja',
            field=models.CharField(help_text='Pipe-separated roles for the typewriter animation, e.g. Software Engineer | System Architect', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='headline_pt',
            field=models.CharField(help_text='Pipe-separated roles for the typewriter animation, e.g. Software Engineer | System Architect', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='headline_zh_hans',
            field=models.CharField(help_text='Pipe-separated roles for the typewriter animation, e.g. Software Engineer | System Architect', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_description_ar',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_description_de',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_description_fr',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_description_ja',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_description_pt',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_description_zh_hans',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_title_ar',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_title_de',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_title_es',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_title_fr',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_title_ja',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_title_pt',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_title_zh_hans',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tagline_ar',
            field=models.CharField(blank=True, help_text='Short intro shown below the headline, e.g. I solve complex problems and build software that lasts.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tagline_de',
            field=models.CharField(blank=True, help_text='Short intro shown below the headline, e.g. I solve complex problems and build software that lasts.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tagline_en',
            field=models.CharField(blank=True, help_text='Short intro shown below the headline, e.g. I solve complex problems and build software that lasts.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tagline_es',
            field=models.CharField(blank=True, help_text='Short intro shown below the headline, e.g. I solve complex problems and build software that lasts.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tagline_fr',
            field=models.CharField(blank=True, help_text='Short intro shown below the headline, e.g. I solve complex problems and build software that lasts.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tagline_ja',
            field=models.CharField(blank=True, help_text='Short intro shown below the headline, e.g. I solve complex problems and build software that lasts.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tagline_pt',
            field=models.CharField(blank=True, help_text='Short intro shown below the headline, e.g. I solve complex problems and build software that lasts.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tagline_zh_hans',
            field=models.CharField(blank=True, help_text='Short intro shown below the headline, e.g. I solve complex problems and build software that lasts.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ar',
            field=models.TextField(help_text='Markdown supported for detail page', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_de',
            field=models.TextField(help_text='Markdown supported for detail page', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(help_text='Markdown supported for detail page', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_es',
            field=models.TextField(help_text='Markdown supported for detail page', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_fr',
            field=models.TextField(help_text='Markdown supported for detail page', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ja',
            field=models.TextField(help_text='Markdown supported for detail page', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_pt',
            field=models.TextField(help_text='Markdown supported for detail page', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_zh_hans',
            field=models.TextField(help_text='Markdown supported for detail page', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='summary_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='summary_de',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='summary_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='summary_es',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='summary_fr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='summary_ja',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='summary_pt',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='summary_zh_hans',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_zh_hans',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_ja',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_pt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_zh_hans',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='name_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='name_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='name_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='name_ja',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='name_pt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='name_zh_hans',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
