# Generated by Django 5.1.15 on 2026-04-05 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_add_persian_translation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('contact_notification', 'Contact Notification'), ('admin_reply', 'Admin Reply'), ('admin_new_email', 'Admin New Email')], max_length=50, unique=True)),
                ('subject', models.CharField(help_text='Use {placeholders} for dynamic content, e.g. {subject}, {name}', max_length=200)),
                ('html_body', models.TextField(help_text='HTML email body. Use {placeholders} for dynamic content.')),
                ('text_body', models.TextField(blank=True, help_text='Plain text fallback. Auto-stripped from HTML if left blank.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline_bn',
            field=models.CharField(help_text='Pipe-separated roles for the typewriter animation, e.g. Software Engineer | System Architect', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline_fa',
            field=models.CharField(help_text='Pipe-separated roles for the typewriter animation, e.g. Software Engineer | System Architect', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline_hi',
            field=models.CharField(help_text='Pipe-separated roles for the typewriter animation, e.g. Software Engineer | System Architect', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline_hu',
            field=models.CharField(help_text='Pipe-separated roles for the typewriter animation, e.g. Software Engineer | System Architect', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline_it',
            field=models.CharField(help_text='Pipe-separated roles for the typewriter animation, e.g. Software Engineer | System Architect', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline_ko',
            field=models.CharField(help_text='Pipe-separated roles for the typewriter animation, e.g. Software Engineer | System Architect', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline_mi',
            field=models.CharField(help_text='Pipe-separated roles for the typewriter animation, e.g. Software Engineer | System Architect', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline_ro',
            field=models.CharField(help_text='Pipe-separated roles for the typewriter animation, e.g. Software Engineer | System Architect', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline_ru',
            field=models.CharField(help_text='Pipe-separated roles for the typewriter animation, e.g. Software Engineer | System Architect', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline_sm',
            field=models.CharField(help_text='Pipe-separated roles for the typewriter animation, e.g. Software Engineer | System Architect', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline_tr',
            field=models.CharField(help_text='Pipe-separated roles for the typewriter animation, e.g. Software Engineer | System Architect', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline_ur',
            field=models.CharField(help_text='Pipe-separated roles for the typewriter animation, e.g. Software Engineer | System Architect', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tagline_bn',
            field=models.CharField(blank=True, help_text='Short intro shown below the headline, e.g. I solve complex problems and build software that lasts.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tagline_fa',
            field=models.CharField(blank=True, help_text='Short intro shown below the headline, e.g. I solve complex problems and build software that lasts.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tagline_hi',
            field=models.CharField(blank=True, help_text='Short intro shown below the headline, e.g. I solve complex problems and build software that lasts.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tagline_hu',
            field=models.CharField(blank=True, help_text='Short intro shown below the headline, e.g. I solve complex problems and build software that lasts.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tagline_it',
            field=models.CharField(blank=True, help_text='Short intro shown below the headline, e.g. I solve complex problems and build software that lasts.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tagline_ko',
            field=models.CharField(blank=True, help_text='Short intro shown below the headline, e.g. I solve complex problems and build software that lasts.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tagline_mi',
            field=models.CharField(blank=True, help_text='Short intro shown below the headline, e.g. I solve complex problems and build software that lasts.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tagline_ro',
            field=models.CharField(blank=True, help_text='Short intro shown below the headline, e.g. I solve complex problems and build software that lasts.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tagline_ru',
            field=models.CharField(blank=True, help_text='Short intro shown below the headline, e.g. I solve complex problems and build software that lasts.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tagline_sm',
            field=models.CharField(blank=True, help_text='Short intro shown below the headline, e.g. I solve complex problems and build software that lasts.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tagline_tr',
            field=models.CharField(blank=True, help_text='Short intro shown below the headline, e.g. I solve complex problems and build software that lasts.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tagline_ur',
            field=models.CharField(blank=True, help_text='Short intro shown below the headline, e.g. I solve complex problems and build software that lasts.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_bn',
            field=models.TextField(help_text='Markdown supported for detail page', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_fa',
            field=models.TextField(help_text='Markdown supported for detail page', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_hi',
            field=models.TextField(help_text='Markdown supported for detail page', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_hu',
            field=models.TextField(help_text='Markdown supported for detail page', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_it',
            field=models.TextField(help_text='Markdown supported for detail page', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_ko',
            field=models.TextField(help_text='Markdown supported for detail page', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_mi',
            field=models.TextField(help_text='Markdown supported for detail page', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_ro',
            field=models.TextField(help_text='Markdown supported for detail page', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_ru',
            field=models.TextField(help_text='Markdown supported for detail page', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_sm',
            field=models.TextField(help_text='Markdown supported for detail page', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_tr',
            field=models.TextField(help_text='Markdown supported for detail page', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_ur',
            field=models.TextField(help_text='Markdown supported for detail page', null=True),
        ),
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('body_preview', models.TextField()),
                ('from_identity', models.CharField(help_text='Display name and email', max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('contact_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='portfolio.contactmessage')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sent Email',
                'verbose_name_plural': 'Sent Emails',
                'ordering': ['-sent_at'],
            },
        ),
    ]
