# Generated by Django 5.1.15 on 2026-04-05 13:14

from django.db import migrations


def seed_templates(apps, schema_editor):
    """Seed the three default email templates."""
    EmailTemplate = apps.get_model("portfolio", "EmailTemplate")

    from portfolio.email import _get_defaults

    for name, data in _get_defaults().items():
        EmailTemplate.objects.update_or_create(
            name=name,
            defaults={
                "subject": data["subject"],
                "html_body": data["html_body"],
                "text_body": data["text_body"],
                "is_active": True,
            },
        )


def unseed_templates(apps, schema_editor):
    EmailTemplate = apps.get_model("portfolio", "EmailTemplate")
    EmailTemplate.objects.filter(
        name__in=["contact_notification", "admin_reply", "admin_new_email"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_emailtemplate_alter_profile_headline_bn_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_templates, unseed_templates),
    ]
