# Generated by Django 5.1.15 on 2026-05-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_profile_full_name_ar_profile_full_name_bn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Human-readable name for this configuration (e.g. 'Postmark — Production').", max_length=100)),
                ('smtp_host', models.CharField(max_length=200)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_user', models.CharField(max_length=200)),
                ('smtp_password', models.CharField(blank=True, help_text='Stored as-is. Leave blank in the form to keep the existing value.', max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('from_name', models.CharField(help_text="Display name shown to recipients, e.g. 'Farzam Mehdi'.", max_length=100)),
                ('from_email', models.EmailField(help_text='Address shown in the From: header. Most providers require this to match the SMTP user. If you want replies to land in a different inbox, use the Reply-To fields below.', max_length=254)),
                ('reply_to_name', models.CharField(blank=True, max_length=100)),
                ('reply_to_email', models.EmailField(blank=True, help_text='Optional. Where recipient replies should land.', max_length=254)),
                ('is_active', models.BooleanField(default=False, help_text='Only one configuration can be active at a time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configurations',
                'ordering': ['-is_active', 'label'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='only_one_active_email_configuration')],
            },
        ),
    ]
