# Generated by Django 5.1.15 on 2026-05-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_emailconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['name', '-is_active', 'label'], 'verbose_name': 'Email Template', 'verbose_name_plural': 'Email Templates'},
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='label',
            field=models.CharField(blank=True, help_text='Optional human-readable label to distinguish multiple templates of the same category.', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(choices=[('contact_notification', 'Contact Notification'), ('admin_reply', 'Admin Reply'), ('admin_new_email', 'Admin New Email')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='emailtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name',), name='only_one_active_template_per_name'),
        ),
    ]
