# Generated by Django 5.1.15 on 2026-05-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_emailtemplate_options_emailtemplate_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh-hans', 'Chinese Simplified'), ('ja', 'Japanese'), ('ar', 'Arabic'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('bn', 'Bengali'), ('hi', 'Hindi'), ('ur', 'Urdu'), ('ko', 'Korean'), ('tr', 'Turkish'), ('ro', 'Romanian'), ('hu', 'Hungarian'), ('it', 'Italian'), ('sm', 'Samoan'), ('mi', 'Maori'), ('fa', 'Persian')], default='en', help_text='Locale captured from the contact form. Used to pick the email language for the reply.', max_length=10),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_ar',
            field=models.TextField(help_text='HTML email body. Use {{ placeholders }} for dynamic content.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_bn',
            field=models.TextField(help_text='HTML email body. Use {{ placeholders }} for dynamic content.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_de',
            field=models.TextField(help_text='HTML email body. Use {{ placeholders }} for dynamic content.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_en',
            field=models.TextField(help_text='HTML email body. Use {{ placeholders }} for dynamic content.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_es',
            field=models.TextField(help_text='HTML email body. Use {{ placeholders }} for dynamic content.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_fa',
            field=models.TextField(help_text='HTML email body. Use {{ placeholders }} for dynamic content.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_fr',
            field=models.TextField(help_text='HTML email body. Use {{ placeholders }} for dynamic content.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_hi',
            field=models.TextField(help_text='HTML email body. Use {{ placeholders }} for dynamic content.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_hu',
            field=models.TextField(help_text='HTML email body. Use {{ placeholders }} for dynamic content.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_it',
            field=models.TextField(help_text='HTML email body. Use {{ placeholders }} for dynamic content.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_ja',
            field=models.TextField(help_text='HTML email body. Use {{ placeholders }} for dynamic content.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_ko',
            field=models.TextField(help_text='HTML email body. Use {{ placeholders }} for dynamic content.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_mi',
            field=models.TextField(help_text='HTML email body. Use {{ placeholders }} for dynamic content.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_pt',
            field=models.TextField(help_text='HTML email body. Use {{ placeholders }} for dynamic content.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_ro',
            field=models.TextField(help_text='HTML email body. Use {{ placeholders }} for dynamic content.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_ru',
            field=models.TextField(help_text='HTML email body. Use {{ placeholders }} for dynamic content.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_sm',
            field=models.TextField(help_text='HTML email body. Use {{ placeholders }} for dynamic content.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_tr',
            field=models.TextField(help_text='HTML email body. Use {{ placeholders }} for dynamic content.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_ur',
            field=models.TextField(help_text='HTML email body. Use {{ placeholders }} for dynamic content.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_zh_hans',
            field=models.TextField(help_text='HTML email body. Use {{ placeholders }} for dynamic content.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_ar',
            field=models.CharField(help_text='Use {{ placeholders }} for dynamic content, e.g. {{ subject }}, {{ name }}', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_bn',
            field=models.CharField(help_text='Use {{ placeholders }} for dynamic content, e.g. {{ subject }}, {{ name }}', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_de',
            field=models.CharField(help_text='Use {{ placeholders }} for dynamic content, e.g. {{ subject }}, {{ name }}', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_en',
            field=models.CharField(help_text='Use {{ placeholders }} for dynamic content, e.g. {{ subject }}, {{ name }}', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_es',
            field=models.CharField(help_text='Use {{ placeholders }} for dynamic content, e.g. {{ subject }}, {{ name }}', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_fa',
            field=models.CharField(help_text='Use {{ placeholders }} for dynamic content, e.g. {{ subject }}, {{ name }}', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_fr',
            field=models.CharField(help_text='Use {{ placeholders }} for dynamic content, e.g. {{ subject }}, {{ name }}', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_hi',
            field=models.CharField(help_text='Use {{ placeholders }} for dynamic content, e.g. {{ subject }}, {{ name }}', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_hu',
            field=models.CharField(help_text='Use {{ placeholders }} for dynamic content, e.g. {{ subject }}, {{ name }}', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_it',
            field=models.CharField(help_text='Use {{ placeholders }} for dynamic content, e.g. {{ subject }}, {{ name }}', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_ja',
            field=models.CharField(help_text='Use {{ placeholders }} for dynamic content, e.g. {{ subject }}, {{ name }}', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_ko',
            field=models.CharField(help_text='Use {{ placeholders }} for dynamic content, e.g. {{ subject }}, {{ name }}', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_mi',
            field=models.CharField(help_text='Use {{ placeholders }} for dynamic content, e.g. {{ subject }}, {{ name }}', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_pt',
            field=models.CharField(help_text='Use {{ placeholders }} for dynamic content, e.g. {{ subject }}, {{ name }}', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_ro',
            field=models.CharField(help_text='Use {{ placeholders }} for dynamic content, e.g. {{ subject }}, {{ name }}', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_ru',
            field=models.CharField(help_text='Use {{ placeholders }} for dynamic content, e.g. {{ subject }}, {{ name }}', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_sm',
            field=models.CharField(help_text='Use {{ placeholders }} for dynamic content, e.g. {{ subject }}, {{ name }}', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_tr',
            field=models.CharField(help_text='Use {{ placeholders }} for dynamic content, e.g. {{ subject }}, {{ name }}', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_ur',
            field=models.CharField(help_text='Use {{ placeholders }} for dynamic content, e.g. {{ subject }}, {{ name }}', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_zh_hans',
            field=models.CharField(help_text='Use {{ placeholders }} for dynamic content, e.g. {{ subject }}, {{ name }}', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text_body_ar',
            field=models.TextField(blank=True, help_text='Plain text fallback. Auto-stripped from HTML if left blank.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text_body_bn',
            field=models.TextField(blank=True, help_text='Plain text fallback. Auto-stripped from HTML if left blank.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text_body_de',
            field=models.TextField(blank=True, help_text='Plain text fallback. Auto-stripped from HTML if left blank.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text_body_en',
            field=models.TextField(blank=True, help_text='Plain text fallback. Auto-stripped from HTML if left blank.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text_body_es',
            field=models.TextField(blank=True, help_text='Plain text fallback. Auto-stripped from HTML if left blank.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text_body_fa',
            field=models.TextField(blank=True, help_text='Plain text fallback. Auto-stripped from HTML if left blank.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text_body_fr',
            field=models.TextField(blank=True, help_text='Plain text fallback. Auto-stripped from HTML if left blank.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text_body_hi',
            field=models.TextField(blank=True, help_text='Plain text fallback. Auto-stripped from HTML if left blank.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text_body_hu',
            field=models.TextField(blank=True, help_text='Plain text fallback. Auto-stripped from HTML if left blank.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text_body_it',
            field=models.TextField(blank=True, help_text='Plain text fallback. Auto-stripped from HTML if left blank.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text_body_ja',
            field=models.TextField(blank=True, help_text='Plain text fallback. Auto-stripped from HTML if left blank.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text_body_ko',
            field=models.TextField(blank=True, help_text='Plain text fallback. Auto-stripped from HTML if left blank.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text_body_mi',
            field=models.TextField(blank=True, help_text='Plain text fallback. Auto-stripped from HTML if left blank.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text_body_pt',
            field=models.TextField(blank=True, help_text='Plain text fallback. Auto-stripped from HTML if left blank.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text_body_ro',
            field=models.TextField(blank=True, help_text='Plain text fallback. Auto-stripped from HTML if left blank.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text_body_ru',
            field=models.TextField(blank=True, help_text='Plain text fallback. Auto-stripped from HTML if left blank.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text_body_sm',
            field=models.TextField(blank=True, help_text='Plain text fallback. Auto-stripped from HTML if left blank.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text_body_tr',
            field=models.TextField(blank=True, help_text='Plain text fallback. Auto-stripped from HTML if left blank.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text_body_ur',
            field=models.TextField(blank=True, help_text='Plain text fallback. Auto-stripped from HTML if left blank.', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text_body_zh_hans',
            field=models.TextField(blank=True, help_text='Plain text fallback. Auto-stripped from HTML if left blank.', null=True),
        ),
    ]
