# Generated by Django 5.1.15 on 2026-09-28 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_profile_logo_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.CharField(help_text='Select a validated SFTP release.', max_length=63)),
                ('enabled', models.BooleanField(default=False)),
                ('instructions', models.TextField(blank=True)),
                ('instructions_en', models.TextField(blank=True, null=True)),
                ('instructions_es', models.TextField(blank=True, null=True)),
                ('instructions_fr', models.TextField(blank=True, null=True)),
                ('instructions_de', models.TextField(blank=True, null=True)),
                ('instructions_zh_hans', models.TextField(blank=True, null=True)),
                ('instructions_ja', models.TextField(blank=True, null=True)),
                ('instructions_ar', models.TextField(blank=True, null=True)),
                ('instructions_pt', models.TextField(blank=True, null=True)),
                ('instructions_ru', models.TextField(blank=True, null=True)),
                ('instructions_bn', models.TextField(blank=True, null=True)),
                ('instructions_hi', models.TextField(blank=True, null=True)),
                ('instructions_ur', models.TextField(blank=True, null=True)),
                ('instructions_ko', models.TextField(blank=True, null=True)),
                ('instructions_tr', models.TextField(blank=True, null=True)),
                ('instructions_ro', models.TextField(blank=True, null=True)),
                ('instructions_hu', models.TextField(blank=True, null=True)),
                ('instructions_it', models.TextField(blank=True, null=True)),
                ('instructions_sm', models.TextField(blank=True, null=True)),
                ('instructions_mi', models.TextField(blank=True, null=True)),
                ('instructions_fa', models.TextField(blank=True, null=True)),
                ('disclosure', models.TextField(blank=True)),
                ('disclosure_en', models.TextField(blank=True, null=True)),
                ('disclosure_es', models.TextField(blank=True, null=True)),
                ('disclosure_fr', models.TextField(blank=True, null=True)),
                ('disclosure_de', models.TextField(blank=True, null=True)),
                ('disclosure_zh_hans', models.TextField(blank=True, null=True)),
                ('disclosure_ja', models.TextField(blank=True, null=True)),
                ('disclosure_ar', models.TextField(blank=True, null=True)),
                ('disclosure_pt', models.TextField(blank=True, null=True)),
                ('disclosure_ru', models.TextField(blank=True, null=True)),
                ('disclosure_bn', models.TextField(blank=True, null=True)),
                ('disclosure_hi', models.TextField(blank=True, null=True)),
                ('disclosure_ur', models.TextField(blank=True, null=True)),
                ('disclosure_ko', models.TextField(blank=True, null=True)),
                ('disclosure_tr', models.TextField(blank=True, null=True)),
                ('disclosure_ro', models.TextField(blank=True, null=True)),
                ('disclosure_hu', models.TextField(blank=True, null=True)),
                ('disclosure_it', models.TextField(blank=True, null=True)),
                ('disclosure_sm', models.TextField(blank=True, null=True)),
                ('disclosure_mi', models.TextField(blank=True, null=True)),
                ('disclosure_fa', models.TextField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('check_result', models.CharField(blank=True, editable=False, max_length=300)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_config', to='portfolio.project')),
            ],
        ),
    ]
